package calpoly;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Charlie
 */
public class GuestPanel extends JPanel
{
    private DatabaseHandle handle;
    private int checkInMonth;
    private int checkInDay;
    private int checkInYear;
    private int checkOutMonth;
    private int checkOutDay;
    private int checkOutYear;
    
    /**
     * Creates new form GuestPanel
     */
    public GuestPanel(DatabaseHandle handle) {
      this.handle = handle;
      
      initComponents();
    }

    protected DatabaseHandle getHandle()
    {
        return handle;
    }
    
    protected String getRoomId()
    {
        return roomCodeLabel.getText();
    }
    
    protected double getPrice()
    {
        return Double.parseDouble(priceLabel.getText());
    }
    
    protected void updateCheckIn(int month, int day, int year)
    {
        checkInMonth = month;
        checkInDay = day;
        checkInYear = year;
    }
    
    protected void updateCheckOut(int month, int day, int year)
    {
        checkOutMonth = month;
        checkOutDay = day;
        checkOutYear = year;
    }
    
    public boolean checkDates(int month, int day, int year, JLabel datesLabel)
    {
        if (month == 2 && day > 28)
        {
            if (day == 29  && (year % 4) != 0)
            {
                datesLabel.setText("This isn't a leap year!");
                return false;
            }
            else if (day > 29)
            {
                datesLabel.setText("Invalid check-in day.");
                return false;
            }
        }
                
        if ((month == 1 || month == 3 || month == 5 || month == 7 || month == 8
                || month == 10 || month == 12) && day > 31)
        {
            return false;
        }
        
        if ((month == 4 || month == 6 || month == 9 || month == 11) && day > 30)
        {
            return false;
        }

        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        roomComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        numBedsLabel = new javax.swing.JLabel();
        roomCodeLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bedTypeLabel = new javax.swing.JLabel();
        maxOccupantsLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        decorLabel = new javax.swing.JLabel();
        checkAvailabilityButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        checkInYearSpinner = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        checkOutYearSpinner = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        checkInDaySpinner = new javax.swing.JSpinner();
        checkOutDaySpinner = new javax.swing.JSpinner();
        checkButton = new javax.swing.JButton();
        checkInMonthSpinner = new javax.swing.JSpinner();
        checkOutMonthSpinner = new javax.swing.JSpinner();
        validDatesLabel = new javax.swing.JLabel();

        jLabel1.setText("Select a Room:");

        ArrayList<String> listRooms = new ArrayList<String>();

        handle.createStatement();
        final ResultSet results = handle.executeQuery("SELECT Name FROM Rooms");

        try
        {
            while (results.next())
            {
                listRooms.add(results.getString("Name"));

            }
        }
        catch (java.sql.SQLException e)
        {
            System.out.println(e);
        }
        roomComboBox.setModel(new javax.swing.DefaultComboBoxModel(listRooms.toArray()));
        roomComboBox.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                roomComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Room Information:");

        jLabel3.setText("Room Code:");

        jLabel4.setText("Number of Beds:");

        numBedsLabel.setText("NumBeds");

        roomCodeLabel.setText("Room Code");

        jLabel7.setText("Bed Type:");

        jLabel8.setText("Max Occupants:");

        jLabel9.setText("Price:");

        jLabel10.setText("Decor:");

        bedTypeLabel.setText("BedType");

        maxOccupantsLabel.setText("Max Occ");

        priceLabel.setText("Price");

        decorLabel.setText("Decor");

        checkAvailabilityButton.setText("Check Availability");
        checkAvailabilityButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkAvailabilityButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel3)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(numBedsLabel)
                            .addComponent(bedTypeLabel)
                            .addComponent(maxOccupantsLabel)
                            .addComponent(priceLabel)
                            .addComponent(roomCodeLabel)
                            .addComponent(decorLabel)))
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(checkAvailabilityButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(roomComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(366, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(roomComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(roomCodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(numBedsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(bedTypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(maxOccupantsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(priceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(decorLabel))
                .addGap(18, 18, 18)
                .addComponent(checkAvailabilityButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(224, Short.MAX_VALUE))
        );

        String firstName = (String)roomComboBox.getSelectedItem();

        handle.createStatement();
        final ResultSet firstResults = handle.executeQuery("SELECT * FROM Rooms");

        try
        {
            while (firstResults.next())
            {
                if (firstResults.getString("Name").equals(firstName))
                {
                    roomCodeLabel.setText(firstResults.getString("Id"));
                    numBedsLabel.setText(firstResults.getString("NumBeds"));
                    bedTypeLabel.setText(firstResults.getString("BedType"));
                    maxOccupantsLabel.setText(firstResults.getString("MaxOccupancy"));
                    priceLabel.setText(firstResults.getString("Price"));
                    decorLabel.setText(firstResults.getString("Decor"));
                }
            }

        } catch (java.sql.SQLException e)
        {
            System.out.println(e);
        }

        jTabbedPane1.addTab("Rooms and Rates", jPanel1);

        jLabel5.setText("Check In");

        jLabel6.setText("Check Out");

        jLabel11.setText("Mon:");

        jLabel12.setText("Mon:");

        jLabel13.setText("Day:");

        checkInYearSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"2009", "2010", "2011", "2012", "2013", "2014"}));
        checkInYearSpinner.setMaximumSize(new java.awt.Dimension(47, 20));

        jLabel14.setText("Year:");

        jLabel15.setText("Day:");

        jLabel16.setText("Year:");

        checkOutYearSpinner.setModel(new javax.swing.SpinnerListModel(new String[] {"2009", "2010", "2011", "2012", "2013", "2014"}));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String []
            {
                "Room", "Rate"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);

        jButton2.setText("Place Reservation");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });

        checkInDaySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        checkOutDaySpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        checkButton.setText("Check Dates");
        checkButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                checkButtonActionPerformed(evt);
            }
        });

        validDatesLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabel5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(checkInYearSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(checkInDaySpinner)
                                    .addComponent(checkInMonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(validDatesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(checkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(checkOutYearSpinner)
                                            .addComponent(checkOutDaySpinner)
                                            .addComponent(checkOutMonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(validDatesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(checkOutMonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(checkOutDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(checkOutYearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(5, 5, 5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(checkInYearSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkButton)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(checkInMonthSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(checkInDaySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)))
                .addComponent(jButton2)
                .addGap(7, 7, 7)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        jTabbedPane1.addTab("Reservations", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkAvailabilityButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkAvailabilityButtonActionPerformed
    {//GEN-HEADEREND:event_checkAvailabilityButtonActionPerformed
        CheckAvailability checkAvail = new CheckAvailability(null, false, this);
        checkAvail.setVisible(true);
    }//GEN-LAST:event_checkAvailabilityButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton2ActionPerformed
    {//GEN-HEADEREND:event_jButton2ActionPerformed
        CompleteReservation reservation = new CompleteReservation(null, false, this);
        reservation.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void roomComboBoxActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_roomComboBoxActionPerformed
    {//GEN-HEADEREND:event_roomComboBoxActionPerformed
        String name = (String)roomComboBox.getSelectedItem();
        
        handle.createStatement();
        final ResultSet results = handle.executeQuery("SELECT * FROM Rooms");
        
        try {
            while (results.next()) {
                if (results.getString("Name").equals(name))
                {
                    roomCodeLabel.setText(results.getString("Id"));
                    numBedsLabel.setText(results.getString("NumBeds"));
                    bedTypeLabel.setText(results.getString("BedType"));
                    maxOccupantsLabel.setText(results.getString("MaxOccupancy"));
                    priceLabel.setText(results.getString("Price"));
                    decorLabel.setText(results.getString("Decor"));
                }
            }

        } catch (java.sql.SQLException e) {
                  System.out.println(e);
        }
    }//GEN-LAST:event_roomComboBoxActionPerformed

    private void checkButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_checkButtonActionPerformed
    {//GEN-HEADEREND:event_checkButtonActionPerformed
        int checkInMon = (Integer)checkInMonthSpinner.getValue();
        int checkInDay = (Integer)checkInDaySpinner.getValue();
        int checkInYear = Integer.parseInt((String)checkInYearSpinner.getValue());
        int checkOutMon = (Integer)checkOutMonthSpinner.getValue();
        int checkOutDay = (Integer)checkOutDaySpinner.getValue();
        int checkOutYear = Integer.parseInt((String)checkOutYearSpinner.getValue());

        if (checkInMon > checkOutMon && checkInYear == checkOutYear)
        {
            validDatesLabel.setText("Check-out is before check-in.");
            return;
        }
        else if (checkInDay > checkOutDay && checkInMon == checkOutMon)
        {
            validDatesLabel.setText("Check-out is before check-in.");
            return;
        }
        else if(checkInYear > checkOutYear)
        {
            validDatesLabel.setText("Invalid check-in year.");
            return;
        }
        else
        {
            if (!checkDates(checkInMon, checkInDay, checkInYear, validDatesLabel)
                || !checkDates(checkOutMon, checkOutDay, checkOutYear, validDatesLabel))
            {
                return;
            }
        }

        validDatesLabel.setText("");

        DatabaseHandle handle = getHandle();

        handle.createStatement();
        ResultSet resultSet = handle.executeQuery("");
    }//GEN-LAST:event_checkButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bedTypeLabel;
    private javax.swing.JButton checkAvailabilityButton;
    private javax.swing.JButton checkButton;
    private javax.swing.JSpinner checkInDaySpinner;
    private javax.swing.JSpinner checkInMonthSpinner;
    private javax.swing.JSpinner checkInYearSpinner;
    private javax.swing.JSpinner checkOutDaySpinner;
    private javax.swing.JSpinner checkOutMonthSpinner;
    private javax.swing.JSpinner checkOutYearSpinner;
    private javax.swing.JLabel decorLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel maxOccupantsLabel;
    private javax.swing.JLabel numBedsLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel roomCodeLabel;
    private javax.swing.JComboBox roomComboBox;
    private javax.swing.JLabel validDatesLabel;
    // End of variables declaration//GEN-END:variables
}
